# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: migration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmigration.proto\"\x86\x01\n\x10MigrationPayload\x12&\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x0e.OTPParameters\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\"\xa2\x01\n\rOTPParameters\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12\x1d\n\talgorithm\x18\x04 \x01(\x0e\x32\n.Algorithm\x12\x1b\n\x06\x64igits\x18\x05 \x01(\x0e\x32\x0b.DigitCount\x12\x16\n\x04type\x18\x06 \x01(\x0e\x32\x08.OTPType\x12\x0f\n\x07\x63ounter\x18\x07 \x01(\x03*y\n\tAlgorithm\x12\x19\n\x15\x41LGORITHM_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x41LGORITHM_SHA1\x10\x01\x12\x14\n\x10\x41LGORITHM_SHA256\x10\x02\x12\x14\n\x10\x41LGORITHM_SHA512\x10\x03\x12\x11\n\rALGORITHM_MD5\x10\x04*U\n\nDigitCount\x12\x1b\n\x17\x44IGIT_COUNT_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44IGIT_COUNT_SIX\x10\x01\x12\x15\n\x11\x44IGIT_COUNT_EIGHT\x10\x02*I\n\x07OTPType\x12\x18\n\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rOTP_TYPE_HOTP\x10\x01\x12\x11\n\rOTP_TYPE_TOTP\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'migration_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALGORITHM._serialized_start=321
  _ALGORITHM._serialized_end=442
  _DIGITCOUNT._serialized_start=444
  _DIGITCOUNT._serialized_end=529
  _OTPTYPE._serialized_start=531
  _OTPTYPE._serialized_end=604
  _MIGRATIONPAYLOAD._serialized_start=20
  _MIGRATIONPAYLOAD._serialized_end=154
  _OTPPARAMETERS._serialized_start=157
  _OTPPARAMETERS._serialized_end=319
# @@protoc_insertion_point(module_scope)
